### ISSUE TITLE
When using collabora office the chat system draw twice.

### ISSUE THREAD

**Issue by Luticus** [jsxc/jsxc#452]
When using the collabora office system the chat roster and chat windows are duplicated in the frame that collabora office draws in.  

Newest Nextcloud
Newset jsxc
Newset collabora

Using vivaldi/chrome, not sure if this happens in other browsers yet.

**Comment by Luticus** [comment]
This also happens in firefox

**Comment by MarcelWaldvogel** [comment]
Fixed in the current beta and upcoming 3.1.0

**Comment by Luticus** [comment]
unfortunately ojxsc beta1 does not fix this issue, i'll wait to give ojsxc beta2 a try.

**Comment by MarcelWaldvogel** [comment]
I don't have the problem in jsxc.nextcloud; you might want to try that (it should be compatible)

@sualko I can't find the reference to the frame check in owncloud/jsxc.chat . Did you forget to "backport" that?

**Comment by sualko** [comment]
> Did you forget to "backport" that?

Jup. I fixed that already.
