### ISSUE TITLE
couldn't complete XMPP registration in Nextcloud

### ISSUE THREAD

**Issue by tihom7** [jsxc/jsxc#782]
### Steps to reproduce the behavior
1. error id: dLfoMWVi2Z6WAwvg2QOi
2.
3.

### Environment
- **JSXC version:*3.4.4* 
- **Host system and version:*Nextcloud 15.0.5* 
- **Browser vendor and version:** 
- **Any browser plugins enabled?** 
- **XMPP server vendor and version:** 
- **Is your XMPP server working with other clients as expected?** 

#### Javascript

Sorry we couldn't complete your registration.

Couldn't parse the response. Response code: 500

Please report this to our issue tracker and mention the request id Qo2kR9qUO77pAVd0pD0R.

#### JSXC

```
```

#### XMPP

```
```

#### Host

```
```

**Comment by MarcelWaldvogel** [comment]
Thank you for the feedback. I have fixed the server problem.

**Comment by tihom7** [comment]
Hi,

I still have the same error. ID: 9Xfaz66QS0x8xY3vCdem

Thanks.

**Comment by MarcelWaldvogel** [comment]
Ouch, yes, indeed!

One more bug squatted, hopefully none to go: Could you try again? (Sorry!)

**Comment by tihom7** [comment]
Great success. Thank you very much Marcel.
