### ISSUE TITLE
Can't login into nightly version (4.0) of JSXC

### ISSUE THREAD

**Issue by andypl** [jsxc/jsxc#788]
### Expected behavior
Login into demo instance of JSXC with provided credentials at website: https://www.jsxc.org/example-nightly
### Actual behavior
Cant login to demo instance of JSXC. Nothing happen where clicking button "Log in chat and submitt".
### Steps to reproduce the behavior
1. Enter website https://www.jsxc.org/example-nightly
2. Put "demo.jsxc.ch" as xmpp domain and "/http-bind/" for the bosh url.
3. Put as login: demo0 to demo9 with password demo0 to demo9
3. Click button: "Log in chat and submitt"
### Environment
- **JSXC version:** 4.0.0-git.d31b957, 
- **Host system and version:** 
- **Browser vendor and version:** Chromium, Firefox
- **Any browser plugins enabled?** 
- **XMPP server vendor and version:** jsxc.org
- **Is your XMPP server working with other clients as expected?** Not know, not tested.

#### Javascript

```
re-main prep time: 2 ms
example.js:1 Uncaught SyntaxError: Identifier 'jsxc' has already been declared
    at example.js:1
(anonymous) @ example.js:1
www.jsxc.org/:1 [DOM] Input elements should have autocomplete attributes (suggested: "current-password"): (More info: https://goo.gl/9p2vKq) <input type=​"password" id=​"watch-password" name=​"password" class=​"form-control">​
www.jsxc.org/:1 [DOM] Input elements should have autocomplete attributes (suggested: "current-password"): (More info: https://goo.gl/9p2vKq) <input type=​"password" name=​"password" id=​"password2" class=​"form-control">​
```

#### JSXC

```
```

**Comment by sualko** [comment]
Thanks for your report. I fixed the issue. Happy testing.

**Comment by andypl** [comment]
Thx. It's fixed for Chromium, but still not work for Firefox. I use 67.03 version.

**Comment by sualko** [comment]
Sorry, I can't reproduce the problem on FF. Did you force reload the page (clear cache)?

**Comment by andypl** [comment]
> Sorry, I can't reproduce the problem on FF. Did you force reload the page (clear cache)?
Clearing the cache does not fix the problem but it works on "porn mode", so problem is on my instance of Firefox :)

Once again thx for fixing the problem so fast.
